version: '2'
services:
  neo4j:
    image: neo4j:3.1.1
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"

  sirko:
    image: dnesteryuk/sirko:latest
    volumes:
      - sirko.conf:/usr/local/sirko/sirko.conf
    ports:
      - "4000:4000"
    links:
      - neo4j
